### ISSUE TITLE
Ability to make object without id

### ISSUE THREAD

**Issue by kimdv** [Obbut/Puss#1]
It is not always necessary that an object need an id. So is it possible to make an object without id? 

See a user example below. The location dont need an id: 
```
{
	"name": "Mr. Awesome",
	"location": {
		"lat": 10.0,
		"lng": 50.0
	}
}
```

**Comment by Joannis** [comment]
MongoDB requires the `_id` key with a unique value in every model that gets inserted into the database.

**Comment by kimdv** [comment]
Also for objects there not is in collections?
