### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by euwars** [Obbut/Puss#17]
In my project i have multiple services and each service has its own separate database and collections for security reasons. So i would love to still be able to use Meow when models have separated databases not just collections :)

**Comment by Joannis** [comment]
This is currently unsupported. But you can set a collection on a model manually using `static let collection = <my-mongodb-collection>`

I did not test this, but it should work

**Comment by euwars** [comment]
Yes, i'm aware of collections.

**Comment by Joannis** [comment]
Does it work?

**Comment by Joannis** [comment]
Fixed in Meow 2.0
