### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by mbmshafraz** [Obbut/Puss#18]
```
try Meow.init("mongodb://localhost/meow")
let user = User()
try user.save()
let temp = try User.findOne()
print(temp?.name)
```

I am running this code in Mac works fine but when I trying to connect remote MongoDB which is running in Ubuntu it prints nil, it means save not works.

**Comment by Joannis** [comment]
What you're likely experiencing is that the user was inserted (at `save()`) but wasn't written to the disk in MongoDB yet. So it'll be there, but only after a few milliseconds. You can test this by putting a `sleep(1)` or `sleep(5)` between `save()` and `findOne()`.

Another solution would be to add a write concern to the collections.

**Comment by mbmshafraz** [comment]
I checked manually and data is not in the database. Even collection User hasn't created.

**Comment by Joannis** [comment]
Okay, that's a problem, of course. I'll give it a shot to reproduce this. Which version of MongoDB are you using? Did you enable authentication?

**Comment by Joannis** [comment]
If you want to keep a tighter loop you can join out slack as described in the MongoKitten repo: https://github.com/openkitten/mongokitten/#-community

**Comment by mbmshafraz** [comment]
Version 2.6.10
I tried both enabled and disabled auth options. Creating DB workes but not collection

**Comment by Joannis** [comment]
Ah, that explains. MongoDB 2.6 isn't supported by newer drivers, both official and unofficial MongoDb drivers. MongoDB changed a lot after 2.6 (3.0 and 3.2 were huge releases). I bet you'll have a lot better luck with a newer MongoDB server.

See their docs on how to achieve that: https://docs.mongodb.com/master/tutorial/install-mongodb-on-ubuntu/

**Comment by mbmshafraz** [comment]
Thank you very much, it was the problem.
